#!/usr/bin/env bash
set -euxo pipefail

export OpenCV_VERSION=4.0.1
export GGLIB_VERSION=1.51

command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

./01-install-newer-cmake   && \
./02-install-eigen         && \
./03-install-sophus        && \
./04-build-opencv          && \
./05-install-geographiclib && \
./06-install-gtsam


# Export library path
sudo ldconfig
