#!/usr/bin/env bash

run_complete_setup () {
  set -euxo pipefail
  command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }
  
  # Set versions or leave empty if you want latest:
  export sophus_VERSION=""
  export OpenCV_VERSION="4.9.0"
  export GTSAM_VERSION="4.2"
  
  ./01-install-newer-cmake     && \
  ./02-install-eigen           && \
  ./03-install-sophus          && \
  ./04-build-opencv            && \
  ./05-install-geographiclib   && \
  ./06-install-gtsam           && \
  ./07-install-realsense       && \
  ./08-install-camera-library 
  
  # Export library path
  sudo ldconfig
}

run_complete_setup
