#!/usr/bin/env bash

install_cmake () (
    set -euxo pipefail
    command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

    # Install required packages in order to download and install the new repo.
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl gpg

    # Download and install the key
    curl -sSfL https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor - \
    | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg  >/dev/null

    # Add the repository
    source /etc/os-release
    echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ ${UBUNTU_CODENAME} main" | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
    sudo apt-get update

    # Install the kitware-archive-keyring package to ensure that your keyring stays up to date as they rotate keys:
    sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg
    sudo apt-get install -y kitware-archive-keyring

    # Finally, install CMake : )
    sudo apt-get install -y cmake
)

install_cmake
