#!/usr/bin/env bash

install_cmake () (
    set -euxo pipefail
    command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

    # Install required packages in order to download and install the new repo.
    sudo apt update
    sudo apt install curl

    curl -sSfL https://apt.kitware.com/kitware-archive.sh | sudo bash

    # Finally, install CMake
    sudo apt-get install -y cmake
)

install_cmake
