#!/usr/bin/env bash
set -euxo pipefail
command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

# Install Eigen and friends
VERSION_ID=$( grep -Po '(?<=VERSION_ID=")[\d.]+' /etc/os-release )

if [[ "${VERSION_ID}" == "18.04" ]]; then
  sudo apt update && sudo apt install -y \
  libblas-dev \
  liblapack-dev \
  libeigen3-dev
else
  tag=${Eigen_VERSION:-3.4.0}
  sudo apt update && sudo apt install -y \
    cmake \
    curl \
    liblapack-dev
  curl -fsL https://gitlab.com/libeigen/eigen/-/archive/${tag}/eigen-${tag}.tar.gz \
  | tar -zx
  cmake -S ./eigen-${tag} -B ./eigen-${tag}/build -DCMAKE_BUILD_TYPE=Release
  cmake --build ./eigen-${tag}/build --target blas
  sudo cmake --build ./eigen-${tag}/build --target install
  sudo cmake --build ./eigen-${tag}/build/blas --target install
fi

