#!/usr/bin/env bash
set -euxo pipefail
topdir=$(pwd)
tag=${OpenCV_VERSION:-4.0.1}
command -v sudo > /dev/null 2>&1 || function sudo { eval $@ ; }

# Download opencv sources
[[ ! -d "opencv-${tag}" ]] && \
git clone -b ${tag} --depth 1 https://github.com/opencv/opencv.git opencv-${tag}

[[ ! -d "opencv_contrib-${tag}" ]] && \
git clone -b ${tag} --depth 1 https://github.com/opencv/opencv_contrib.git opencv_contrib-${tag}

# Build OpenCV
mkdir -p ./opencv-${tag}/build
cd ./opencv-${tag}/build

cmake .. \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_DOCS=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_JAVA=OFF \
-DBUILD_PROTOBUF=OFF \
-DBUILD_TBB=ON \
-DBUILD_TESTS=OFF \
-DBUILD_PERF_TESTS=OFF \
-DOPENCV_EXTRA_MODULES_PATH="../../opencv_contrib-${tag}/modules/" \
-DOPENCV_ENABLE_NONFREE=ON \
-DWITH_CUDA=ON \
-DBUILD_opencv_{java,js,photo,python}=OFF \
-DBUILD_opencv{\
aruco,bgsegm,bioinspired,ccalib,cnn_3dobj,cvv,datasets,dnn_objdetect,dnns_easily_fooled,dpm,face,freetype,\
fuzzy,hdf,hfs,img_hash,line_descriptor,matlab,optflow,ovis,phase_unwrapping,plot,reg,rgbd,saliency,sfm,shape,stereo,\
structured_light,superres,surface_matching,text,tracking,videostab,xfeatures2d,ximgproc,xobjdetect,xphoto}=OFF \
-DBUILD_opencv_cuda{arithm,bgsegm,codec,features2d,filters,imgproc,legacy,objdetect,optflow,stereo,warping,cudev}=OFF \
&& \
cmake --build . --config release -- -j $(nproc) -Wno-cpp && \
sudo cmake --build . --target install

cd ${topdir}

