#!/usr/bin/env bash
set -euxo pipefail
command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
${SCRIPT_DIR}/02-install-eigen

sudo apt update && sudo apt install -y \
  build-essential \
  git \
  cmake \
  libfmt-dev

[[ ! -d "Sophus" ]] && git clone --depth 1 https://github.com/strasdat/Sophus.git

mkdir -p Sophus/build && cd $_
cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SOPHUS_EXAMPLES=OFF \
  -DBUILD_SOPHUS_TESTS=OFF
cmake --build .
sudo cmake --build . --target install
cd ../..
rm -rf Sophus ~/.cmake/packages/Sophus
