#!/usr/bin/env bash
set -euxo pipefail
command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
${SCRIPT_DIR}/02-install-eigen

sudo apt update && sudo apt install -y \
  build-essential \
  git \
  cmake \
  libfmt-dev

tag=${sophus_VERSION:-1.22.10}
url=https://github.com/strasdat/Sophus/archive/refs/tags/${tag}.tar.gz
curl -fsL "${url}" | tar -zx
cmake -S ./Sophus-${tag} -B ./Sophus-${tag}/build \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SOPHUS_EXAMPLES=OFF \
  -DBUILD_SOPHUS_TESTS=OFF
cmake --build Sophus-${tag}/build
sudo cmake --build Sophus-${tag}/build --target install

rm -rf Sophus* ~/.cmake/packages/Sophus

