#!/usr/bin/env bash
# Build OpenCV from source, and install system wide.
# This version of the script is tailored for Ubuntu 22.04 (jammy).

build_opencv () (
  set -eu
  command -v sudo > /dev/null 2>&1 || { apt -qq update && apt install --no-install-recommends -y sudo; }

  sudo apt update

  # Required
  sudo apt install -y build-essential ccache cmake git

  # GUI
  sudo apt install -y libgtk-3-dev libvtk7-dev

  # Media I/O
  sudo apt install -y libgdal-dev libjpeg-dev libpng-dev libopenjp2-7-dev libopenexr-dev libtiff-dev libwebp-dev

  # Video I/O
  sudo apt install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libgphoto2-dev libcanberra-gtk3-module

  # Parallel framework
  sudo apt install -y libtbb-dev libtbb2

  # Other third-party libraries
  sudo apt install -y libva-dev libeigen3-dev libtesseract-dev

  # Download opencv sources
  sudo apt install -qqy jq
  
  local latest=$(curl -sSf https://api.github.com/repos/opencv/opencv/releases/latest | jq -r '.tag_name')
  local tag="${OpenCV_VERSION:-${latest}}"
  
  [[ ! -d "opencv-${tag}" ]] && \
  curl -SfL https://github.com/opencv/opencv/archive/refs/tags/${tag}.tar.gz | tar -zx

  [[ ! -d "opencv_contrib-${tag}" ]] && \
  curl -SfL https://github.com/opencv/opencv_contrib/archive/refs/tags/${tag}.tar.gz | tar -zx

  # Configure OpenCV
  cmake -S opencv-${tag} -B opencv-${tag}/build \
  -DBUILD_LIST="core,cudev,features2d,imgproc,imgcodecs,highgui,stereo,videoio,viz,xfeatures2d" \
  -DCMAKE_BUILD_TYPE=Release \
  -DOPENCV_EXTRA_MODULES_PATH="opencv_contrib-${tag}/modules/" \
  -DCMAKE_INSTALL_PREFIX="/usr/local" \
  -DBUILD_DOCS=OFF \
  -DBUILD_EXAMPLES=OFF \
  -DBUILD_JAVA=OFF \
  -DBUILD_opencv_python2=OFF \
  -DBUILD_opencv_python3=OFF \
  -DBUILD_PERF_TESTS=OFF \
  -DBUILD_TESTS=OFF \
  -DCPACK_GENERATOR=DEB \
  -DCPACK_MONOLITHIC_INSTALL=ON \
  -DOPENCV_ENABLE_NONFREE=ON \
  -DOPENCV_GENERATE_PKGCONFIG=ON \
  -DOPENCV_IPP_ENABLE_ALL=ON \
  -DWITH_GDAL=ON \
  -DWITH_GPHOTO2=ON \
  -DWITH_GSTREAMER=OFF \
  -DWITH_PROTOBUF=ON \
  -DBUILD_PROTOBUF=ON \
  -DWITH_QT=OFF \
  -DWITH_TBB=ON \
  -DBUILD_TBB=OFF
  
  # Build OpenCV
  cmake --build opencv-${tag}/build --config release -- -j $(nproc)
  
  # Install
  sudo cmake --build opencv-${tag}/build --target install

  # If executed in Dockerfile or container, remove artifacts
  if [[ -f /.dockerenv ]]; then 
      rm -rf opencv*
  fi
)

build_opencv
