#!/usr/bin/env bash
set -euxo pipefail
command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

tag=${GGLIB_VERSION:-1.51}

sudo apt install -y \
  build-essential \
  cmake \
  curl \
  wget  # wget for geographiclib-get-geoids

curl -fsL https://sourceforge.net/projects/geographiclib/files/distrib/GeographicLib-${tag}.tar.gz \
| tar --xform 's/GeographicLib[0-9.-]+/geographiclib/gx' -zx

cmake -S geographiclib -B geographiclib/build -DCMAKE_BUILD_TYPE=Release
sudo cmake --build geographiclib/build --config release --target install
sudo rm -rf geographiclib

