#!/usr/bin/env bash
set -euxo pipefail

command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

sudo apt install -y apt-transport-https ca-certificates gnupg software-properties-common
sudo apt-key adv --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || \
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE

VERSION_CODENAME=$( grep -Po '(?<=VERSION_CODENAME=)\S+' /etc/os-release )
sudo add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo ${VERSION_CODENAME} main" -u
sudo apt install -y librealsense2-dev

if [[ ! -f /.dockerenv ]]; then 
    sudo apt install -y librealsense2-{dkms,utils,dbg}
fi
