---
- name: "CMake : Generate build script"
  ansible.builtin.template:
    src: cmake.j2
    dest: "{{ scripts_destination }}/{{ scripts_names.cmake }}"
    mode: '700'
    owner: "{{ ansible_user }}"
  notify: Install cmake
...
