---
- name: "OpenCV : Load configuration variables"
  ansible.builtin.include_vars: 'opencv-{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml'

- name: "OpenCV : Generate build script"
  ansible.builtin.template:
    src: build-opencv.j2
    dest: "{{ scripts_destination }}/{{ scripts_names.opencv }}"
    mode: '700'
    owner: "{{ ansible_user }}"
  notify: Install opencv
...
