---
- name: Get facts on current container
  community.docker.current_container_facts:

- name: Print information on current container when running in a container
  ansible.builtin.debug:
    msg: "[{{ inventory_hostname }}] ({{ ansible_host }}) is a docker container."
  when: ansible_module_running_in_container

- name: Install JetBrains
  when: not ansible_module_running_in_container
  community.general.snap:
    name: "{{ tek5030_classic_snaps }}"
    state: present
    classic: true
...
