---
- name: Ensure OS is supported
  ansible.builtin.assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_distribution_major_version >= '18'"

- name: Include tasks apt
  ansible.builtin.include_tasks: apt.yml
  args: { apply: { become: true } }

- name: Include tasks bash-git-propmt
  ansible.builtin.include_tasks: bash-git-prompt.yml

- name: Include tasks from install-snaps
  ansible.builtin.include_tasks: install-snaps.yml
  args: { apply: { become: true } }
...
