---
docker_apt_dependencies:
  - ca-certificates
  - curl
  - gnupg

docker_apt_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_keyring: "/etc/apt/keyrings/docker.gpg"
docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
docker_apt_repository: >-
  deb [arch={{ docker_apt_arch }} signed-by={{ docker_apt_keyring }}]
  https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

docker_nvidia_apt_repo_url: https://nvidia.github.io/libnvidia-container
docker_nvidia_apt_key_url: "{{ docker_nvidia_apt_repo_url }}/gpgkey"
docker_nvidia_apt_keyring: "/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg"
docker_nvidia_apt_repository: "deb [signed-by={{ docker_nvidia_apt_keyring }}] {{ docker_nvidia_apt_repo_url }}/stable/deb/$(ARCH) /"
...
